NicolasPetton/Indium

.gitignore
jade-repl.el
jade-webkit.el

I've started from making console output more handsome. 
As console now shows `url:line` I want to use sourcemaps to show actual code lines instead of `bundle.js:1234`

Make console messages interactive as in direct repl evaluation

---

jade-repl.el
jade-scratch.el

Enable completions in the scratch buffer by using the company-jade-repl backend.
I've changed the expression logic for the completions since the current completions only seemed to work for lines with only one symbol (for: `var x = "test".substr(0,2);` f.ex. the completions shown after `"test".` were not correct).

Enable scratch buffer completions

---

indium-breakpoint.el
test/jade-breakpoint-test.el

Fix #32
(this code has been written by @NicolasPetton on my computer)

Only add breakpoint overlay when it is not already there

---

indium.el

The group definition was missing (although there are references to it).

Add indium group definition

---

doc/Indium.texi
indium-backend.el
indium-interaction.el
indium-webkit.el
sphinx-doc/code-evaluation.rst

Usage:
```lisp
(add-hook 'indium-update-script-source-hook
(lambda (url)
(indium-eval (format "window.dispatchEvent(new CustomEvent('patch', {detail: {url: '%s'}}))"
url))))
```
and
```js
window.addEventListener("patch", (event) => {
console.log("Patched @ " + new Date().toTimeString().substring(0, 8), event.detail);
// rerender, etc
});
```

Add indium-update-script-source-hook

---

indium-interaction.el
indium-render.el

Inspired by http://endlessparentheses.com/eval-result-overlays-in-emacs-lisp.html, I wanted to try to make indium show evaled results inline with the code in a similar fasion to what [CIDER](https://cider.readthedocs.io/) does.
This pr does not add such functionality in indium, but shows how exposing a hook to handle results evaled with `indium-eval-last-node` can allow for extensions to accomplish this, along with keeping results shown in the minibuffer.
With such a hook in place, this is what it would take to show fontified, evaled results, inline with other code e.g. using cider's machinery
```elisp
(autoload 'cider--make-result-overlay "cider-overlays")
(defun t/overlay-indium (r)
(cider--make-result-overlay (indium-fontify-js "%s" r) :where (point) :duration 'command))
(add-hook …
```

Add `indium-interaction-eval-node-hook` to allow for eval hooks, e.g for overlays

---

indium-repl.el

Hi, most repls (and shell in emacs) also use these binds to navigate back and forth
on the input history.

Bind C-<up> and C-<down> to also navigate on history.

---

Cask
indium-script.el
indium-sourcemap.el
indium.el
test/unit/indium-script-test.el
test/unit/indium-sourcemap-test.el

Replace sourcemap.el with a modified version of the sourcemap implementation of
kite.

Replace sourcemap.el dependency (fix #113)

---

indium-debugger.el

* indium-debugger.el (indium-debugger-evaluate): When called with a prefix
argument, inspect the result of the evaluation.

Add a keybinding to inspect the result of evals in the debugger

---

indium-repl.el
indium-v8.el
test/unit/indium-chrome-test.el

This patch will try to recycle the buffer if already exists.
Fixes #97.

Avoid creating a new buffer if already exists.

---

indium-nodejs.el

This is helpful when programatically binding to a debugger session and the host/port/path are already known

Allow `indium-connect-to-nodejs` to be called from elisp

---

indium-v8.el

* indium-v8.el (indium-backend-add-breakpoint): Set breakpoint ids even when
they cannot be resolved, and add them to the map of breakpoints in the current
connection.  This way breakpoints that are not yet resolved can still be
manipulated.

Always set breakpoint ids

---

indium-nodejs.el
sphinx-doc/setup.rst
test/unit/indium-nodejs-test.el

Hi,
Sometimes it's really handy to just copy-and-paste the url to connect
to a node instance for debugging.

Connect to nodejs with url.

---

server/adapters/cdp/helpers.js
server/adapters/cdp/index.js
server/package.json
server/spec/adapters/cdp/index-spec.js

Fix github #175.
Previous implementation was sometimes considering `state.scripts` to
be an array and sometimes an object literal. This resulted in the
variable to contain `undefined` values after each call to
`scriptAdded`.

Fix jumping to a location in debugger

---

server/helpers/workspace.js
server/spec/helpers/workspace-spec.js
sphinx-doc/debugger.rst
sphinx-doc/setup.rst

Hello!  I've added a feature that allows the kind of mapping of scripts I mentioned in [issue #188](https://github.com/NicolasPetton/Indium/issues/188).  It's simple, and I've tried to match your coding, configuration naming, and documentation style everywhere.  I hope you will find it useful.

Add <scriptPathOverrides> feature.

---

indium-structs.el
test/unit/indium-breakpoint-test.el
test/unit/indium-structs-test.el

* indium-structs.el (indium-breakpoint-location): Fix movement to
return the proper location. Rationale: given that (point-min) is 1,
after (goto-char (point-min)), 0 must be passed to forward-char
instead of 1. This is particularly important if the breakpoint is
at (point-max) because forward-char would raise an error.
* test/unit/indium-breakpoint-test.el: Add test.

Fix how a breakpoint location is computed

---

server/server/connection.js

- This matches the behavior of chrome-type connections.
- It will stop emitting success messages when connection error has occurred.

Short-circuit on error when connecting to node

---

indium-chrome.el

Fix #187 
* indium-chrome.el (indium-chrome-data-dir): Use a directory in .emacs.d by
default.

Set the default chrome data dir in .emacs.d

---

Makefile
indium-client.el
indium-structs.el
indium.el
test/unit/indium-client-test.el

This commit extracts part of indium-client.el into a reusable library (that I would like to use for a basecamp integration): [json-process-client.el](https://github.com/NicolasPetton/Indium/files/3365484/json-process-client.txt). If you agree with this extraction, I can take care of creating a repo (under `DamienCassou/`) or you can do it yourself (which would make more sense because you are the author). I will take care of creating a PR for MELPA unless you want to do it yourself.
* indium-client.el:
(indium-client--connection)
(indium-client--process)
(indium-client--callbacks): Remove to have `indium-client--application`
instead.
(indium-client--application): New variable to save the return value of
`json-process-client-start`.
(indium-client-start): Rewrite to call …

Extract part of indium-client.el into a new library.

---

server/helpers/workspace.js

path.join resolves to Windows paths containing back slashes.
All the tests use Unix paths containing forward slashes.
Node doesn't care about using paths with forward slashes on Windows, but will
always return paths with back slashes. Using path.posix means the tests can be
cross platform.

fix(test): use path.posix to allow cross platform testing

---

indium-breakpoint.el
indium-client.el

Emacs 27 is out, and has no map-put.
This PR to remove the macro from Indium.
https://github.com/NicolasPetton/Indium/issues/245

Remove map-put from the code.

---

indium-breakpoint.el

FYI, if Emacs starts in daemon mode then the call to `(display-graphic-p)` almost always returns `nil`; it only returns `t` if run in the context of a graphical client frame, which has to be manually created after the daemon finishes initialization.
Therefore, as currently written, an Emacs started in daemon mode that loads this package sometime during startup doesn't define the debugger breakpoint bitmaps.  So even if the user is using a graphical frame, nothing shows up in the fringe when adding breakpoints or breaking to them.
No harm results from taking out this `(display-graphic-p)` check.  Terminal / daemon Emacs already defines plenty of bitmaps with no ill effect (evaluate `fringe-bitmaps` in a terminal Emacs to see for yourself).

Fix missing debugger fringe indicators in daemon mode

---

indium-client.el
indium-nodejs.el
server/README.md
server/server/connection.js

I'm developing a node project with one of those tools that restarts the server on every code change.  Indium as-is doesn't support this use case because node doesn't cleanly shut down until the debugging client disconnects.
Fortunately the CDP library already supports a disconnect command.  Here's a quick PR to implement the disconnect command in the elisp library and hook it up to the node process watchdog.
The updated node process filter is watching for the string "Waiting for the debugger to disconnect" because that's what I see on my machine with node v12.20.1.  I'd appreciate some help testing older versions to make sure that's a broad enough match.

Send a CDP "disconnect" command when the NodeJS server expects it
